### ISSUE TITLE
Don't see nice UI suggested by "Linter in action!"

### ISSUE THREAD

**Issue by jwimberley** [AtomLinter/linter-gcc#169]
The README advertises a nice looking, color coded display of errors and warnings under the header "Linter in action!" However, this is not what I when using Linter myself. Instead, I see the following:

![atom](https://user-images.githubusercontent.com/12789262/37852965-0464954c-2ebb-11e8-80f0-146067af8062.png)

without the helpful error/warning color coding, and in general less aesthetically pleasing. I am not sure if this is a configuration setting within linter-gcc, linter, linter-ui-default, or is some custom JSON, but it would be nice to be able to make the linter output appear as shown in the README.

**Comment by Arcanemagus** [comment]
That's the old `linter` v1 UI shown in the image. `linter` v2 moved to splitting out the UI to a separate package (`linter-ui-default`) and the style you see above. You _may_ be interested in [`linter-ui-plus`](https://atom.io/packages/linter-ui-plus) however note that it doesn't have tooltips implemented.

Since this is just a provider, you can also try out [atom-ide-ui](https://ide.atom.io/) which this will plug into.
